-- CreateEnum
CREATE TYPE "DIRECTION" AS ENUM ('MEDICAL', 'EDUCATION', 'SOCIAL');

-- AlterEnum
ALTER TYPE "StatusType" ADD VALUE 'SUCCESSFUL';

-- AlterTable
ALTER TABLE "FundRaiser" ADD COLUMN     "program" "DIRECTION" NOT NULL DEFAULT 'MEDICAL';
